# Basic Linear Algebra Concepts
> Examining some basic concepts of liner algebra using python libraries

- toc: true
- branch: main
- badges: true
- categories: [jupyter, maths, linear-algebra, tensors, matrices]

### Intro to Linear Algebra

References:
1. https://github.com/jonkrohn/ML-foundations

In [23]:
import numpy as np
import math
import torch
import tensorflow as tf
import matplotlib.pyplot as plt

#### Scalar Tensors


Pytorch tensors can be used for operations on the GPU or CPU, unlike numpy arrays, by casting the tensor to a CUDA data type. 

Tensorflow tensors are also immutable, and created using wrappers.

In [24]:
# Example scalar pytorch tensor
x = torch.tensor(10, dtype=torch.int64)
print(f"Type: {x.dtype}, Shape: {x.shape}")

Type: torch.int64, Shape: torch.Size([])


In [25]:
# Example scalar tensorflow tensor
x = tf.constant(10, dtype=tf.int64)
x

<tf.Tensor: shape=(), dtype=int64, numpy=10>

#### Vector Transposition

In [26]:
x = np.array([[5,6,7]]) #Need extra brackets else shape will be (,3) (1D, not 2D)
print(f"x = {x} \nShape = {x.shape}")

x = [[5 6 7]] 
Shape = (1, 3)


In [27]:
x_t = x.T
print(f"x transposed:\n{x_t} \nShape = {x_t.shape}")

x transposed:
[[5]
 [6]
 [7]] 
Shape = (3, 1)


In [28]:
x = torch.tensor([5,6,7])
print(f"x = {x} \nShape = {x.shape}")

x = tensor([5, 6, 7]) 
Shape = torch.Size([3])


In [29]:
#L2 Norm - euclidean distance
x = np.array([[5,6,7]])
np.linalg.norm(x)

10.488088481701515

In [30]:
# L1 Norm
np.sum(np.absolute(x))

18

In [31]:
# Squared L2 Norm
x = np.array([5,6,7])
np.dot(x,x)

110

In [32]:
# Max norm
np.max(np.abs(x))

7

In [33]:
#Orthogonal
i = np.asarray([1,0])
j = np.asarray([0,1])
np.dot(i,j)

0

#### Matrices (2-Tensor)

In [34]:
X = np.array([[5,3],[6,8],[2,10]])
print(f"{X}\n Shape: {X.shape} Size: {X.size}")

[[ 5  3]
 [ 6  8]
 [ 2 10]]
 Shape: (3, 2) Size: 6


In [35]:
X[:,0] # left column

array([5, 6, 2])

In [36]:
X[1,:] # middle row

array([6, 8])

In [37]:
#pytorch
X = torch.tensor([[5,3],[6,8],[2,10]])
print(f"{X}\n Shape: {X.shape}")

tensor([[ 5,  3],
        [ 6,  8],
        [ 2, 10]])
 Shape: torch.Size([3, 2])


In [38]:
#Tensorflow
X = tf.constant([[5,3],[6,8],[2,10]])
print(f"Rank: {tf.rank(X)} Shape: {tf.shape(X)}")

Rank: 2 Shape: [3 2]


#### n-Tensors

In [39]:
X = torch.zeros([5,2,4,2])
X.shape

torch.Size([5, 2, 4, 2])

In [40]:
X = tf.zeros([5,2,4,2])
print(f"Rank: {tf.rank(X)}")

Rank: 4


#### Tensor Operations

In [41]:
X = np.array([[5,3],[6,8],[2,10]])
print(f"X*2 = \n{X*2}\n  X+2 =\n{X+2}")

X*2 = 
[[10  6]
 [12 16]
 [ 4 20]]
  X+2 =
[[ 7  5]
 [ 8 10]
 [ 4 12]]


In [43]:
X = torch.tensor([[5,3],[6,8],[2,10]])
print(f"X*2 = \n{torch.mul(X,2)}\n  X+2 =\n{torch.add(X,2)}")

X*2 = 
tensor([[10,  6],
        [12, 16],
        [ 4, 20]])
  X+2 =
tensor([[ 7,  5],
        [ 8, 10],
        [ 4, 12]])


#### Elementwise Product  

If tensors have the same size, operations can be aplied elementwise, this is the Hadamard product: $$\boldsymbol X \odot \boldsymbol Y$$

In [44]:
X = np.array([[5,3],[6,8],[2,10]])
Y = X + 5
print(X*Y) ##dot product, not matrix multiplication

[[ 50  24]
 [ 66 104]
 [ 14 150]]
