### Intro to Linear Algebra

References:
1. https://github.com/jonkrohn/ML-foundations

In [6]:
import numpy as np
import math
import torch
import tensorflow as tf
import matplotlib.pyplot as plt

2022-04-30 12:34:00.264674: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-30 12:34:00.264689: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


#### Scalar Tensors


Pytorch tensors can be used for operations on the GPU or CPU, unlike numpy arrays, by casting the tensor to a CUDA data type. 

Tensorflow tensors are also immutable, and created using wrappers.

In [12]:
# Example scalar pytorch tensor
x = torch.tensor(10, dtype=torch.int64)
print(f"Type: {x.dtype}, Shape: {x.shape}")

Type: torch.int64, Shape: torch.Size([])


In [14]:
# Example scalar tensorflow tensor
x = tf.constant(10, dtype=tf.int64)
x

<tf.Tensor: shape=(), dtype=int64, numpy=10>

#### Vector Transposition

In [19]:
x = np.array([[5,6,7]]) #Need extra brackets else shape will be (,3) (1D, not 2D)
print(f"x = {x} \nShape = {x.shape}")

x = [[5 6 7]] 
Shape = (1, 3)


In [23]:
x_t = x.T
print(f"x transposed:\n{x_t} \nShape = {x_t.shape}")

x transposed:
[[5]
 [6]
 [7]] 
Shape = (3, 1)


In [25]:
x = torch.tensor([5,6,7])
print(f"x = {x} \nShape = {x.shape}")

x = tensor([5, 6, 7]) 
Shape = torch.Size([3])


In [26]:
#L2 Norm - euclidean distance
x = np.array([[5,6,7]])
np.linalg.norm(x)

10.488088481701515

In [29]:
# L1 Norm
np.sum(np.absolute(x))

18

In [28]:
# Squared L2 Norm
x = np.array([5,6,7])
np.dot(x,x)

110

In [31]:
# Max norm
np.max(np.abs(x))

7

In [32]:
#Orthogonal
i = np.asarray([1,0])
j = np.asarray([0,1])
np.dot(i,j)

0

#### Matrices (2-Tensor)

In [41]:
X = np.array([[5,3],[6,8],[2,10]])
print(f"{X}\n Shape: {X.shape} Size: {X.size}")

[[ 5  3]
 [ 6  8]
 [ 2 10]]
 Shape: (3, 2) Size: 6


In [38]:
X[:,0] # left column

array([5, 6, 2])

In [39]:
X[1,:] # middle row

array([6, 8])

In [44]:
#pytorch
X = torch.tensor([[5,3],[6,8],[2,10]])
print(f"{X}\n Shape: {X.shape}")

tensor([[ 5,  3],
        [ 6,  8],
        [ 2, 10]])
 Shape: torch.Size([3, 2])


In [45]:
#Tensorflow
X = tf.constant([[5,3],[6,8],[2,10]])
print(f"Rank: {tf.rank(X)} Shape: {tf.shape(X)}")

Rank: 2 Shape: [3 2]


#### n-Tensors

In [49]:
X = torch.zeros([5,2,4,2])
X.shape

torch.Size([5, 2, 4, 2])

In [52]:
X = tf.zeros([5,2,4,2])
print(f"Rank: {tf.rank(X)}")

Rank: 4
