### Intro to Linear Algebra

References:
1. https://github.com/jonkrohn/ML-foundations

In [2]:
import numpy as np
import math
import torch
import tensorflow as tf
import matplotlib.pyplot as plt

#### Scalar Tensors


Pytorch tensors can be used for operations on the GPU or CPU, unlike numpy arrays, by casting the tensor to a CUDA data type. 

Tensorflow tensors are also immutable, and created using wrappers.

In [3]:
# Example scalar pytorch tensor
x = torch.tensor(10, dtype=torch.int64)
print(f"Type: {x.dtype}, Shape: {x.shape}")

Type: torch.int64, Shape: torch.Size([])


In [4]:
# Example scalar tensorflow tensor
x = tf.constant(10, dtype=tf.int64)
x

2022-05-02 12:45:13.935875: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-02 12:45:13.978973: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-02 12:45:13.979100: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-02 12:45:13.979916: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

<tf.Tensor: shape=(), dtype=int64, numpy=10>

#### Vector Transposition

In [5]:
x = np.array([[5,6,7]]) #Need extra brackets else shape will be (,3) (1D, not 2D)
print(f"x = {x} \nShape = {x.shape}")

x = [[5 6 7]] 
Shape = (1, 3)


In [6]:
x_t = x.T
print(f"x transposed:\n{x_t} \nShape = {x_t.shape}")

x transposed:
[[5]
 [6]
 [7]] 
Shape = (3, 1)


In [7]:
x = torch.tensor([5,6,7])
print(f"x = {x} \nShape = {x.shape}")

x = tensor([5, 6, 7]) 
Shape = torch.Size([3])


In [8]:
#L2 Norm - euclidean distance
x = np.array([[5,6,7]])
np.linalg.norm(x)

10.488088481701515

In [9]:
# L1 Norm
np.sum(np.absolute(x))

18

In [10]:
# Squared L2 Norm
x = np.array([5,6,7])
np.dot(x,x)

110

In [11]:
# Max norm
np.max(np.abs(x))

7

In [12]:
#Orthogonal
i = np.asarray([1,0])
j = np.asarray([0,1])
np.dot(i,j)

0

#### Matrices (2-Tensor)

In [13]:
X = np.array([[5,3],[6,8],[2,10]])
print(f"{X}\n Shape: {X.shape} Size: {X.size}")

[[ 5  3]
 [ 6  8]
 [ 2 10]]
 Shape: (3, 2) Size: 6


In [14]:
X[:,0] # left column

array([5, 6, 2])

In [15]:
X[1,:] # middle row

array([6, 8])

In [16]:
#pytorch
X = torch.tensor([[5,3],[6,8],[2,10]])
print(f"{X}\n Shape: {X.shape}")

tensor([[ 5,  3],
        [ 6,  8],
        [ 2, 10]])
 Shape: torch.Size([3, 2])


In [17]:
#Tensorflow
X = tf.constant([[5,3],[6,8],[2,10]])
print(f"Rank: {tf.rank(X)} Shape: {tf.shape(X)}")

Rank: 2 Shape: [3 2]


#### n-Tensors

In [18]:
X = torch.zeros([5,2,4,2])
X.shape

torch.Size([5, 2, 4, 2])

In [19]:
X = tf.zeros([5,2,4,2])
print(f"Rank: {tf.rank(X)}")

Rank: 4


#### Tensor Operations

In [20]:
X = np.array([[5,3],[6,8],[2,10]])
print(f"X*2 = \n{X*2}\n  X+2 =\n{X+2}")

X*2 = 
[[10  6]
 [12 16]
 [ 4 20]]
  X+2 =
[[ 7  5]
 [ 8 10]
 [ 4 12]]


In [21]:
X = torch.tensor([[5,3],[6,8],[2,10]])
print(f"X*2 = \n{torch.mul(X,2)}\n  X+2 =\n{torch.add(X,2)}")

X*2 = 
tensor([[10,  6],
        [12, 16],
        [ 4, 20]])
  X+2 =
tensor([[ 7,  5],
        [ 8, 10],
        [ 4, 12]])


#### Elementwise Product  

If tensors have the same size, operations can be aplied elementwise, this is the Hadamard product: $$\boldsymbol X \odot \boldsymbol Y$$ It produces a tensor that is the same shape as the input, unlike the dot product which will produce a scalar value.

In [22]:
X = np.array([[5,3],[6,8],[2,10]])
Y = X + 5
print(X*Y) ##dot product, not matrix multiplication

[[ 50  24]
 [ 66 104]
 [ 14 150]]


#### Tensor Reduction

In [36]:
print(X.sum(), torch.sum(torch.tensor([[5,3],[6,8],[2,10]])))
print(tf.reduce_sum(tf.constant([[5,3],[6,8],[2,10]])))
print(X.sum(axis=0), X.sum(axis=1)) #along specific axes
print(torch.sum(torch.tensor([[5,3],[6,8],[2,10]]),0))
print(torch.sum(torch.tensor([[5,3],[6,8],[2,10]]),1))
print(tf.reduce_sum(tf.constant([[5,3],[6,8],[2,10]]),0))
print(tf.reduce_sum(tf.constant([[5,3],[6,8],[2,10]]),1))

34 tensor(34)
tf.Tensor(34, shape=(), dtype=int32)
[13 21] [ 8 14 12]
tensor([13, 21])
tensor([ 8, 14, 12])
tf.Tensor([13 21], shape=(2,), dtype=int32)
tf.Tensor([ 8 14 12], shape=(3,), dtype=int32)


#### Dot Product

The vectors must be of the same length or shape for the element-wise multiplication to occurr.

In [38]:
X = np.array([5,3,6,8,2,10])
Y = X + 1
print(np.dot(X,Y))

272


In [40]:
print(torch.dot(torch.tensor([5,3,6,8,2,10]),torch.add(torch.tensor([5,3,6,8,2,10]),1)))

tensor(272)


In [41]:
print(tf.reduce_sum(tf.multiply(tf.constant([5,3,6,8,2,10]),tf.add(tf.constant([5,3,6,8,2,10]),1))))

tf.Tensor(272, shape=(), dtype=int32)


### Matrices
#### Frobenius Norm

In [45]:
X = np.array([[5,3],[6,8],[2,10]])
print(np.linalg.norm(X))
print(torch.norm(torch.tensor([[5.,3],[6,8],[2,10]])))
print(tf.norm(tf.constant([[5.,3],[6,8],[2,10]])))

15.427248620541512
tensor(15.4272)
tf.Tensor(15.427248, shape=(), dtype=float32)


#### Matrix Multiplication

In [52]:
A = np.array([[3,4],[5,6],[7,8]])
b = np.array([1,2])
print(np.dot(A,b)) #infers dot product vs matrix multiplication based on shape
C = torch.tensor([[3,4],[5,6],[7,8]])
d = torch.tensor([1,2])
print(torch.matmul(C,d))
E = tf.constant([[3,4],[5,6],[7,8]])
f = tf.constant([1,2])
print(tf.linalg.matvec(E,f))

tensor([11, 17, 23])
tf.Tensor([11 17 23], shape=(3,), dtype=int32)


In [58]:
A = np.array([[3,4],[5,6],[7,8]])
b = np.array([[1,9],[2,0]])
print(np.dot(A,b)) 
C = torch.tensor([[3,4],[5,6],[7,8]])
d = torch.tensor([[1,9],[2,0]])
print(torch.matmul(C,d))
E = tf.convert_to_tensor(A)
f = tf.convert_to_tensor(b)
print(tf.matmul(E,f))

[[11 27]
 [17 45]
 [23 63]]
tensor([[11, 27],
        [17, 45],
        [23, 63]])
tf.Tensor(
[[11 27]
 [17 45]
 [23 63]], shape=(3, 2), dtype=int64)


#### Matrix Inversion

In [63]:
X = np.array([[4,2],[-5,-3]])
X_inv = np.linalg.inv(X)
y = np.array([4,-7])
print(w:= np.dot(X_inv,y))
print(np.dot(X,w))

[-1.  4.]
[ 4. -7.]
